//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.26 at 07:28:02 PM EET 
//


package com.example.test;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.gems package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Precious_QNAME = new QName("http://www.example.com/gems", "precious");
    private final static QName _Semiprecious_QNAME = new QName("http://www.example.com/gems", "semiprecious");
    private final static QName _Gem_QNAME = new QName("http://www.example.com/gems", "gem");
    private final static QName _Gems_QNAME = new QName("http://www.example.com/gems", "gems");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.gems
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Precious }
     * 
     */
    public Precious createPrecious() {
        return new Precious();
    }

    /**
     * Create an instance of {@link GemType }
     * 
     */
    public GemType createGemType() {
        return new GemType();
    }

    /**
     * Create an instance of {@link Semiprecious }
     * 
     */
    public Semiprecious createSemiprecious() {
        return new Semiprecious();
    }

    /**
     * Create an instance of {@link Gems }
     * 
     */
    public Gems createGems() {
        return new Gems();
    }

    /**
     * Create an instance of {@link VisualParameters }
     * 
     */
    public VisualParameters createVisualParameters() {
        return new VisualParameters();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Precious }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/gems", name = "precious", substitutionHeadNamespace = "http://www.example.com/gems", substitutionHeadName = "gem")
    public JAXBElement<Precious> createPrecious(Precious value) {
        return new JAXBElement<Precious>(_Precious_QNAME, Precious.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Semiprecious }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/gems", name = "semiprecious", substitutionHeadNamespace = "http://www.example.com/gems", substitutionHeadName = "gem")
    public JAXBElement<Semiprecious> createSemiprecious(Semiprecious value) {
        return new JAXBElement<Semiprecious>(_Semiprecious_QNAME, Semiprecious.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/gems", name = "gem")
    public JAXBElement<GemType> createGem(GemType value) {
        return new JAXBElement<GemType>(_Gem_QNAME, GemType.class, null, value);
    }


    //добавил вручную
    @XmlElementDecl(namespace = "http://www.example.com/gems", name = "gems")
    public JAXBElement<Gems> createGems(Gems value) {
        return new JAXBElement<Gems>(_Gems_QNAME, Gems.class, null, value);
    }

}
